#!/bin/bash


pkill nowplaying  # prevents multiple instances running if this script is called multiple times


find /mnt/files.ntfs/Multimedia/Music -type f ! \( -iname "desktop.ini" -o -iname "thumbs.db" \) > /tmp/playlist.m3u

shuf /tmp/playlist.m3u -o /tmp/playlist.m3u

cvlc --play-and-exit /tmp/playlist.m3u </dev/null &>/dev/null&

nowplaying &