#!/bin/bash


pkill vlc   # prevents multiple instances running if this script is called multiple times

read -p "artist or song: " audio

find /mnt/files.ntfs/Multimedia/Music -type f ! \( -iname "desktop.ini" -o -iname "thumbs.db" \) > /tmp/playlist.m3u

grep -ie "$audio" /tmp/playlist.m3u > /tmp/playlist2.m3u
cvlc --play-and-exit /tmp/playlist2.m3u </dev/null &>/dev/null&

nowplaying &
