#!/bin/bash

#adds entire directory of choice to a playlist in /tmp folder
#use nowplaying scipt to see song info in panel 

pkill nowplaying  # prevents multiple instances running if this script is called multiple times

find ~/Multimedia/Music -type f -not -path '*/\.*' | sort > /tmp/playlist.m3u

cvlc --random --play-and-exit /tmp/playlist.m3u </dev/null &>/dev/null&

nowplaying &
