#!/bin/bash
#stops player and updates current album art icon to transparent icon for panel

playerctl stop

ICON_PATH="$HOME/.icons/now-playing.png"
TRANSPARENT_ICON="$HOME/.icons/transparent.png"
PANEL_CONFIG="$HOME/.config/wayfire/wf-shell.ini"

if [ "$(readlink "$ICON_PATH" 2>/dev/null)" != "$TRANSPARENT_ICON" ]; then
    ln -sfn "$TRANSPARENT_ICON" "$ICON_PATH"
    #touch "$PANEL_CONFIG"
fi
